name: 'whiskey_ml'
version: '1.0.0'

profile: 'whiskey_ml'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:       
  - "target"
  - "dbt_packages"

vars:
  records: complete

models:
  whiskey_ml:
    +persist_docs:
      relation: true
      columns: true
    +submission_method: serverless
    
    staging:
      +schema: staging
      +materialized: table
    
    production:
      +schema: analytics
      +materialized: table
      
      machine_learning:
        +tags: ["machine_learning"]
